[project]
name = "accounting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.3",
    "asyncpg>=0.31.0",
    "fastapi[all]>=0.128.0",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.46",
]
